# Generated by Django 5.0.6 on 2024-06-12 06:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chatgpt", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="embeddingfulltextsearchcontent",
            table="embedding_fulltext_search_content",
        ),
    ]
