# Generated by Django 5.0.6 on 2024-06-12 04:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatgpt", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="user_id",
            field=models.CharField(default="admin", max_length=255),
        ),
        migrations.AlterField(
            model_name="message",
            name="user_id",
            field=models.CharField(default="admin", max_length=255),
        ),
    ]
