# Generated by Django 5.0.6 on 2024-06-12 06:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chatgpt", "0002_alter_embeddingfulltextsearchcontent_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="embeddingfulltextsearchcontent",
            table=None,
        ),
    ]
