# Generated by Django 5.0.6 on 2024-06-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatgpt", "0005_message_delete_chat"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="EmbeddingFulltextSearchContent",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("c0", models.TextField()),
                ("string_value", models.TextField(null=True)),
            ],
            options={
                "db_table": "embedding_fulltext_search_content",
            },
        ),
    ]
